[package]
edition = "2021"
name = "manipulate-linear-memory"
version = "0.4.0"

[dependencies]
anyhow = "1"
wasmedge-sdk = { git = "https://github.com/second-state/wasmedge-rust-sdk.git", branch = "refactor/sdk_preview" }
