[package]
edition = "2021"
name = "manipulate-linear-memory"
version = "0.3.0"

[dependencies]
anyhow = "1"
wasmedge-sdk = {git = "https://github.com/apepkuss/wasmedge-rust-sdk", branch = "test/release-0.9.0-alpha.1"}
