[package]
edition = "2021"
name = "naive-math-plugin"
version = "0.4.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmedge-sdk = {git = "https://github.com/WasmEdge/wasmedge-rust-sdk.git", branch = "main", features = ["ffi"]}
