[package]
edition = "2021"
name = "naive-math-plugin"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmedge-sdk = { path = "/home/sam/workspace/downloads/WasmEdge/bindings/rust/wasmedge-sdk", features = [
    "ffi",
] }
