[package]
edition = "2021"
name = "naive-math-plugin"
version = "0.3.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmedge-sdk = { git = "https://github.com/apepkuss/wasmedge-rust-sdk.git", branch = "update-test-code", features = [
    "ffi",
] }
