[package]
edition = "2021"
name = "naive-math-plugin"
version = "0.3.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmedge-sdk = { git = "https://github.com/apepkuss/wasmedge-rust-sdk", branch = "test/release-0.9.0-alpha.1", features = [
    "ffi",
] }
