[package]
name = "define-host-func-with-host-data"
version = "0.4.0"
edition = "2021"

[dependencies]
wasmedge-sdk = { git = "https://github.com/second-state/wasmedge-rust-sdk.git", branch = "refactor/sdk_preview" }
