[package]
name = "run-ggml-llama-inference"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmedge-sdk ={ git = "https://github.com/apepkuss/wasmedge-rust-sdk.git", branch = "main", features = ["wasi_nn"] }
