[package]
name = "run-ggml-llama-inference"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmedge-sdk = { git = "https://github.com/second-state/wasmedge-rust-sdk.git", branch = "refactor/sdk_preview", features=["wasi_nn"] }

