[package]
name = "run-wasm-app"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmedge-sdk = {path = "../../../wasmedge-rust-sdk", features = ["async"]}
tokio = {version = "1", features = ["full"]}