[package]
edition = "2021"
name = "run-wasm-func-in-aot-mode"
version = "0.1.0"

[dependencies]
wasmedge-sdk = {git = "https://github.com/WasmEdge/wasmedge-rust-sdk.git", branch = "main", features = ["aot"]}
