[package]
edition = "2021"
name = "run-wasm-func-in-aot-mode"
version = "0.4.0"

[dependencies]
wasmedge-sdk = { git = "https://github.com/second-state/wasmedge-rust-sdk.git", branch = "refactor/sdk_preview", features = ["aot"] }
