[package]
name = "main-app"
version = "0.4.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
wasmedge-sdk = { git = "https://github.com/second-state/wasmedge-rust-sdk.git", branch = "refactor/sdk_preview" }

