[package]
name = "main-app"
version = "0.3.0"
edition = "2021"

[dependencies]
wasmedge-sdk = {git = "https://github.com/WasmEdge/wasmedge-rust-sdk", branch = "main", features = ["async"]}
tokio = {version = "1", features = ["full"]}