[package]
name = "main-app"
version = "0.3.0"
edition = "2021"

[dependencies]
wasmedge-sdk = {git = "https://github.com/apepkuss/wasmedge-rust-sdk", branch = "test/release-0.9.0-alpha.1", features = ["async"]}
tokio = {version = "1", features = ["full"]}