[package]
name = "define-async-host-func-with-host-data"
version = "0.4.0"
edition = "2021"

[dependencies]
tokio = {version = "1.28", features = ["full"]}
wasmedge-sdk = {version = "0.11.0", features = ["async"]}
