[package]
edition = "2021"
name = "define-async-host-func"
version = "0.4.0"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
wasmedge-sdk = { git = "https://github.com/second-state/wasmedge-rust-sdk.git", branch = "refactor/sdk_preview" }
