[package]
edition = "2021"
name = "define-async-host-func"
version = "0.3.0"

[dependencies]
tokio = {version = "1.28", features = ["full"]}
wasmedge-sdk = {git = "https://github.com/apepkuss/wasmedge-rust-sdk.git", branch = "update-test-code", features = ["async"]}
