[package]
edition = "2021"
name = "define-async-host-func"
version = "0.1.0"

[dependencies]
tokio = {version = "1.28", features = ["full"]}
wasmedge-sdk = {git = "https://github.com/WasmEdge/wasmedge-rust-sdk.git", branch = "main", features = ["async"]}
