[package]
edition = "2021"
name = "run-mandelbrot-in-parallel"
version = "0.4.0"

[dependencies]
wasmedge-sdk = { git = "https://github.com/apepkuss/wasmedge-rust-sdk.git", branch = "update-test-code", features = [
    "aot",
] }
