[package]
edition = "2021"
name = "run-mandelbrot-in-parallel"
version = "0.1.0"

[dependencies]
wasmedge-sdk = { git = "https://github.com/WasmEdge/wasmedge-rust-sdk.git", branch = "main", features = [
    "aot",
] }
