[package]
edition = "2021"
name = "define-host-func-with-string-args"
version = "0.3.0"

[dependencies]
wasmedge-sdk = {git = "https://github.com/apepkuss/wasmedge-rust-sdk.git", branch = "update-test-code"}
