[package]
edition = "2021"
name = "object-detection-via-wasinn"
version = "0.4.0"

[dependencies]
wasmedge-sdk = { git = "https://github.com/second-state/wasmedge-rust-sdk.git", branch = "refactor/sdk_preview", features = [
    "wasi_nn",
] }
