[package]
edition = "2021"
name = "object-detection-via-wasinn"
version = "0.4.0"

[dependencies]
wasmedge-sdk = { git = "https://github.com/apepkuss/wasmedge-rust-sdk.git", branch = "update-test-code", features = [
    "wasi_nn",
] }
