[package]
edition = "2021"
name = "object-detection-via-wasinn"
version = "0.3.0"

[dependencies]
wasmedge-sdk = { git = "https://github.com/WasmEdge/wasmedge-rust-sdk", branch = "main", features = [
    "wasi_nn",
] }
