[package]
edition = "2021"
name = "object-detection-via-wasinn"
version = "0.1.0"

[dependencies]
wasmedge-sdk = { git = "https://github.com/apepkuss/wasmedge-rust-sdk", branch = "test/release-0.9.0-alpha.1", features = [
    "wasi_nn",
] }
