name: rust-sdk-examples

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - dev
      - "sdk-*"

  pull_request:
    branches:
      - main
      - dev

jobs:
  build_ubuntu:
    name: Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        rust: [1.70.0, 1.69, 1.68]
    container:
      image: wasmedge/wasmedge:ubuntu-build-clang

    steps:
      - name: Checkout WasmEdge RustSDK Examples
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout WasmEdge Runtime
        uses: actions/checkout@v3
        with:
          repository: WasmEdge/WasmEdge
          path: WasmEdge

      - name: Build WasmEdge with Release mode
        working-directory: WasmEdge
        run: |
          apt update
          apt install -y software-properties-common libboost-all-dev llvm-15-dev liblld-15-dev ninja-build
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_PROCESS=On .
          cmake --build build
          cmake --install build
          ldconfig

      - name: Install Rust-stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: wasm32-wasi
      
      - name: async-wasi
        working-directory: async-wasi
        run: |
          cargo build -p wasm-app --target wasm32-wasi --release
          cargo run -p run-wasm-app -- ./target/wasm32-wasi/release/wasm-app.wasm
      
      - name: async-wasi-socket
        working-directory: async-wasi-socket
        run: |
          cargo build -p socket-addr --target wasm32-wasi --release
          cargo run -p main-app -- ./target/wasm32-wasi/release/socket-addr.wasm

      - name: run call-wasm-lib-from-host example
        working-directory: call-wasm-lib-from-host
        run: |
          cargo build -p wasm-lib --target wasm32-wasi --release
          cargo run -p call-wasm-lib -- ./target/wasm32-wasi/release/wasm_lib.wasm 5
